language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"

env:
  - DJANGO="https://www.djangoproject.com/download/1.6c1/tarball/"
  - DJANGO="django==1.5.5 --use-mirrors"
  - DJANGO="django==1.4.9 --use-mirrors"

install:
  - pip install $DJANGO
  - pip install psycopg2 django-localflavor --use-mirrors
  - export PYTHONPATH=.

script:
  - python distance/runtests/runtests.py

before_script:
  - psql -c 'create database dev_db;' -U postgres

matrix:
  exclude:
    - python: "3.3"
      env: DJANGO="django==1.4.9 --use-mirrors"
